@urlBase = http://localhost:5000

GET {{urlBase}}/students/ HTTP/1.1
###

GET http://localhost:5000/students/615d29d332e23f3142294a08 HTTP/1.1
###

POST http://localhost:5000/students HTTP/1.1
content-type: application/json

{
    "dni": 101001,
    "name": "Jota Jota Pelaez",
    "age": 56,
    "semester": 3
}
###

DELETE {{urlBase}}/students/615d29d332e23f3142294a08

###
PUT http://localhost:5000/students/615e4ada0d87fddf07402cc3
content-type: application/json

{
    "dni": 546589,
    "name": "Juan Manuel Cuervo",
    "age": 16,
    "semester": 3
}
