@urlBase = http://localhost:5000

GET {{urlBase}}/usuarios/ HTTP/1.1
###

GET {{urlBase}}/usuarios/61685f2bdb1621296c3f500d HTTP/1.1
###

POST {{urlBase}}/usuarios HTTP/1.1
content-type: application/json

{
    "dni": 1035918779,
    "nombre": "Anderson",
    "apellido": "Charry",
    "rol": "ADMIN",
    "celular": 31477818132,
    "email": "CHARRY072013@gmail.com",
    "ingreso": "04101996" 
}
###

DELETE {{urlBase}}/usuarios/43469

###
PUT {{urlBase}}/usuarios/5469
content-type: application/json

{
    "dni": 5469,
"nombre": "Anderson",
    "apellido": "Charry",
    "rol": "ADMIN",
    "celular": 3147781832,
    "email": "charry072031@gmail.com.com",
    "ingreso": "960410" 
}
